name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache Gradle packages
        uses: burrunan/gradle-cache-action@v1
      - name: Build & test
        run: ./gradlew --no-daemon --info build
